#! /bin/bash

IR_OUTPUT_DIR=ir/output

if [ ! -d "$IR_OUTPUT_DIR" ]; then
	echo "INFO: creating the $IR_OUTPUT_DIR directory"
	mkdir $IR_OUTPUT_DIR
else
	echo "INFO: the $IR_OUTPUT_DIR already exists"
fi
